<?php

/**
 * @file
 * Contains pdf_generator_drupal_module.module
 */

// Permet d'implémenter l'interface de routage de Drupal.
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Ce hook permet de gérer la route de l'aide du module.
 *
 * Implements pdf_generator_drupal_module_help().
 */
function pdf_generator_drupal_module_help($route_name, RouteMatchInterface $route_match)
    {
        switch ($route_name) {
            case 'help.page.pdf_generator_drupal_module':
            $output = '';
            $output .= '<h3>' . t('À propos') . '</h3>';
            $output .= '<p>' . t('Ce module permet de générer un fichier PDF.') . '</p>';

            // Utilisation du module.
            $output .= '<h3>' . t('Uses') . '</h3>';
            $output .= '<div>';
            $output .= '<dt>' . t('Creating Paragraphs types') . '</dt>';
            $output .= '<dd>' . t('<em>Paragraphs types</em> can be created by ...') . '<dd>';
            $output .= '</div>';

            // Dépendances du module.
            $output .= '<h4>' . t('Dépendances du module') . '</h4>';
            $output .= '<p>' . t('Ce module à pour packages de dépendances :') . '</p>';
            $output .= '<ul>';
            $output .= '<li>' . t('<a href=":link">esiee/pdf_generator_composer_package</a>', [':link' => 'https://packagist.org/packages/esiee/pdf_generator_composer_package',]) . '</li>';
            $output .= '</ul>';

            return $output;
        break;
    }
}

/**
 * Implements pdf_generator_drupal_module_theme().
 */
function pdf_generator_drupal_module_theme()
{
  $theme = [];

  return $theme;
}
