<?php

/**
 * @file
 * Contains pdfgenerator.module
 */

// Permet d'implémenter l'interface de routage de Drupal.
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */

function pdfgenerator_help($route_name, RouteMatchInterface $route_match) {
	switch ($route_name) {
		case 'help.page.pdfgenerator':
			$output = '';
			$output .= '<h3>' . t('À propos') . '</h3>';
			$output .= '<p>' . t('Ce module permet de générer un fichier PDF.') . '</p>';

			// Utilisation du module.
			$output .= '<h3>' . t('Uses') . '</h3>';
			$output .= '<div>';
			$output .= '<dt>' . t('Creating Paragraphs types') . '</dt>';
			$output .= '<dd>' . t('<em>Paragraphs types</em> can be created by ...') . '<dd>';
			$output .= '</div>';

			// Dépendances du module.
			$output .= '<h4>' . t('Dépendances du module') . '</h4>';
			$output .= '<p>' . t('Ce module à pour packages de dépendances :') . '</p>';
			$output .= '<ul>';
			$output .= '<li>' . t('<a href=":link">esiee/pdf_generator</a>', [':link' => 'https://packagist.org/packages/esiee/pdf_generator',]) . '</li>';
			$output .= '</ul>';

			return $output;
			break;
	}
}

/**
 * Implements hook_theme().
 */

function pdfgenerator_theme() {
	$theme = [];

	return $theme;
}

function pdfgenerator_page_top(array &$page) {
	// Add 'Back to content editing' link on preview page.
	$route_match = \Drupal::routeMatch();
	var_dump($route_match, $page);
	exit;
}
