<?php

/**
 * @file
 * Contains pdfgenerator.module
 */

// Permet d'implémenter l'interface de routage de Drupal.
use Drupal\Core\Routing\RouteMatchInterface;

use Drupal\Core\Url;
/**
 * Ce hook permet de gérer la route de l'aide du module.
 *
 * Implements hook_help().
 */
function pdfgenerator_help($route_name, RouteMatchInterface $route_match)
{
        switch ($route_name) {
            case 'help.page.pdfgenerator':
            $output = '';
            $output .= '<h3>' . t('À propos') . '</h3>';
            $output .= '<p>' . t('Ce module permet de générer un fichier PDF.') . '</p>';

            // Utilisation du module.
            $output .= '<h3>' . t('Uses') . '</h3>';
            $output .= '<div>';
            $output .= '<dt>' . t('Creating Paragraphs types') . '</dt>';
            $output .= '<dd>' . t('<em>Paragraphs types</em> can be created by ...') . '<dd>';
            $output .= '</div>';

            // Dépendances du module.
            $output .= '<h4>' . t('Dépendances du module') . '</h4>';
            $output .= '<p>' . t('Ce module à pour packages de dépendances :') . '</p>';
            $output .= '<ul>';
            $output .= '<li>' . t('<a href=":link">esiee/pdf_generator</a>', [':link' => 'https://packagist.org/packages/esiee/pdf_generator',]) . '</li>';
            $output .= '</ul>';

            return $output;
        break;
		}
}
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_view_alter() for nodes.
 */
function pdfButtonModule_node_view_alter(array &$build, EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display): void
{

	// Vérifiez si le type de contenu est "article".
	if ($entity->getType() === 'article' || $entity->getType() === 'article_image' ) {
		$url = Url::fromRoute('pdfButtonModule.export_pdf', ['node' => $entity->id()]);
		$url_options = [
			'attributes' => [
				'class' => [
					// Add or remove CSS classes here
					'button',
					'button--small'
				],
			],
		];
		$url->setOptions($url_options);

		// Ajoutez le lien d'export PDF au rendu du nœud.
		$build['pdfButtonModule_export_pdf_link'] = [
			'#type' => 'link',
			'#title' => t('Export PDF test'),
			'#url' => $url,
		];
	}
}

/**
 * Implements hook_theme().
 */
function pdfgenerator_theme()
{
  $theme = [];

  return $theme;
}
